/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Player {
  nickname: string;
  color: string;
  goalCount: number;
  racetimeStatus: RacetimeStatusDisconnected | RacetimeStatusConnected;
}
export interface RacetimeStatusDisconnected {
  connected: false;
}
export interface RacetimeStatusConnected {
  connected: true;
  /**
   * Racetime username connected to this player for the race
   */
  username: string;
  /**
   * Racetime race status
   */
  status: string;
  /**
   * Race finish time (ISO 8601 duration)
   */
  finishTime?: string;
}
