/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Platform {
  /**
   * The name of the platform (e.g., PC, Xbox, PlayStation)
   */
  name: string;
}
